### ISSUE TITLE
Syntax error when using type declaration

### ISSUE THREAD

**Issue by jchavarri** [rebench/rebench.github.io#5]
When writing `type t;` (or any other type) in a Reason box, I'm getting a syntax error.

**Comment by jchavarri** [comment]
![image](https://user-images.githubusercontent.com/220424/38466057-c3624c36-3b23-11e8-9ccf-e0c9ecd0e7d7.png)

**Comment by glennsl** [comment]
Test case code is put inside a function that will be executed repeatedly while being masured, and therefore can't include toplevel definitions. You should put these in setup instead.

From the help modal:

> A test is a unit of code that will be measured while executed repeatedly. Anything you do not want to measure should be put in the setup block. Furthermore, setup code is toplevel, can include type and module defintions, and anything defined there will be available in every test. The tests on the other hand are isolated by being wrapped in a function.
